In [2]:
import numpy as np
a1 = np.random.rand(4)
a1

array([0.65220075, 0.34284015, 0.82046899, 0.86084618])

In [3]:
a2 = np.random.rand(4,1)
a2

array([[0.14616124],
       [0.49356861],
       [0.72440006],
       [0.61271838]])

In [4]:
a1.shape
a2.shape

(4, 1)

In [5]:
a1.shape

(4,)

In [7]:
a2.shape

(4, 1)

In [11]:
a3=np.array([[1, 2, 3, 4]])
a3.shape

(1, 4)

In [13]:
a4=np.arange(1,4,1)
a4

array([1, 2, 3])

In [14]:
a5 = np.linspace(1,4,4)
a5

array([1., 2., 3., 4.])

In [15]:
a5.shape==a1.shape


True

In [20]:
m1=[[ 0,1,2,3,4,5],[6,7,8,9,10,11],[12,13,14,15,16,17],[18,19,20,21,22,23],[24,25,26,28,29],[30,32,32,33,34,35]]
m1

[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23],
 [24, 25, 26, 28, 29],
 [30, 32, 32, 33, 34, 35]]

In [27]:
m1[[2,4],[2,4]]

TypeError: list indices must be integers or slices, not tuple

In [32]:
import re
s="ACBCAC"

re.findall('AC', s)

['AC', 'AC']

In [33]:
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
L

5

In [36]:

([(]\d{3}[)]\s\d{3}[-]\d{4}).'ffice of Research Administration: (734) 647-6333 | 4325 North Quad'

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (<ipython-input-36-2b69361c0331>, line 1)

In [38]:
import numpy as np 
old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0 
print(old)

[[0 0 1]
 [1 1 1]]


In [39]:
s = 'ACBCAC'
re.findall('[^A]C', s)

['BC']

In [40]:
re.findall('^AC', s)


['AC']

In [41]:
re.findall('AC', s)

['AC', 'AC']

In [42]:
re.findall('^[AC]', s)

['A']

In [43]:
m1


[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23],
 [24, 25, 26, 28, 29],
 [30, 32, 32, 33, 34, 35]]

In [48]:
m1=np.array[[ 0,1,2,3,4,5],[6,7,8,9,10,11],[12,13,14,15,16,17],[18,19,20,21,22,23],[24,25,26,28,29],[30,32,32,33,34,35]]

TypeError: 'builtin_function_or_method' object is not subscriptable